# server.port=9000
# server.servlet.context-path=/api

server:
    port: 8080
    servlet:
        context-path: /api


# spring data jpa

spring:
    datasource:
        username: sa
        password: password
        url: jdbc:h2:mem:menu_microservice
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
            path: /database


logging:
  level:
    root: INFO
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type]': TRACE